src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js
Completed page Prog 1/2
Completed page Prog 2/2
Started Database Page 1
=> Finished Prog1, Prog2, started Database Page

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js
Added paragraph definitions for completed pages for easier reading.
Fixed units on XTK to NM, set as absolute value and fixed Left of Track "L" indication.
Added Page Refresh code to the PROG 1 and PROG 2 pages.
=> Organized, fixed XTK, added pagerefresh to prog

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
Updated 'nav bar' at bottom of PFD with live UTC and RAT
Updated 'nav bar' at bottom of MFD with GS TAS RAT SAT ISA
Removed GS and TAS from ND on PFD and MFD
=> PFD MFD Nav Bar Edits and GS/TAS Removed

PackageDefinitions/workingtitle-gx-metapackage.xml, README.md, src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.js, workingtitle-project-gx.xml
In regard to the name "gx":
The idea behind that is, that on one side, it is not realy one g1000 anymore and on the other side, the garmins are very dependend due its "share" folder files. When it comes to the build process it could raise problems, when we handle it seperatly.
How do you think about it?
best regards,
Argonox
=> Retrofit g3000 - removed as requested the bonanza and the skylane from the metadata file

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DirectToPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
**Key Features:**
-Fixed Direct To routing when attempting to go direct to the IAF
-Fixed LEGS page listing to include all flight plan and approach waypoints
-Added PERF pages and functions, including takeoff, landing and fuel management
-Added IDX pages and functions, including progress pages, approach details
-Fixed PFD and MFD NAV BAR details
**- In Direct To Page:**
1. Adjusted waypoint listing to show origin, departure, enroute, arrival and first approach fix
2. Added proper handling for activating a direct to the IAF in an approach without causing the plane to fly back to a prior fix and auto activating the approach from present position.
**- In LEGS Page:**
1. Fixed errors in display of flight plan waypoints
2. Added approach waypoints to legs listing
**- In IDX/InitRefIndexPage:** …
=> Cj4 cwb direct to v0.1

src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/model/CJ4_Cockpit.xml
* Light up all the FMC push buttons
* Light up Floodlight knobs at the cabin ceiling
Wonder if it could be done better via template, but I dont know.
LWR Panel lighting must be done in AS3000.xml which I didn't want to touch now.
=> CJ4: Light up all the push buttons

src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/model/CJ4_Cockpit.xml, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
This PR implements some changes to the layout basics. Please lets discuss anything you dont like or want to have different.
+ Scratchpad brackets and alignment
+ Label/Line alignment (lines moved more to the border)
+ Less space between the lines
+ Changes to vertical font height (temporary experiment)
+ CSS filters to give it that "fuzzy" display look (just an experiment)
+ Make space for message line
+ Introduced logic for "EXEC" element controlled by a property in CJ4_FMC
**BEFORE**
**AFTER**
**RL**
=> CJ4: Basic layout changes in FMC

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/PFD/AirspeedIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
Created LVARS from perfinit page to track each of the six vspeeds and whether they were set by FMS or PFD manually.
Adjusted airspeed indicator to interrogate these bool LVARS to determine color of vSpeed and tape marker.
Still to do (future):
1) Have vSpeed titles change color in the text SVG under the airspeed tape; currently set to white.
2) Add Green Dot Speed
3) Confirm logic for when tape vSpeed markers appear or disappear based on what's set and what the current IAS and/or phase of flight is.
=> Added proper colors and logic to vSpeeds on PFD and adjusted AoA to only appear when Flaps are set to 35

src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js, src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/AS1000/PFD/AS1000_PFD.js
* move WX radar to a page in the map page group
* only show WX page if radar is onboard
* kill weird "GPS" softkey that existed to toggle radar
* improve MAP soft menu incl. adding track up switch.
SPECIAL BONUS!
* PFD config menu doesn't override DTO/FPL popups any more.
=> MFD menu improvements

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js
Some changes to the Index page and some perf menus so it aligns with the ProLine21 version that is in the CJ4 FMS.  I noticed on the Perf page, it shows Chris' vspeed FMCSet code in there in red, perhaps I didn't pull the main the get the latest and it is showing that as a change?
=> Template changes for CJ4 accuracy

src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
=> Don't display wind data while on ground

src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/flight_model.cfg
Added to increase stabilizer effectiveness to improve autopilot pitch tracking
=> Added for autopilot improvement

src/workingtitle-core-library/html_ui/Pages/VCockpit/Instruments/Shared/WorkingTitle/FileHandler.js
=> overlooked class rename

src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js, src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
1) move the AS1000 MFD wind code into CommonPFD_MFD like the core
files did in 1.8.
2) only display NO WIND DATA on PFD when on the ground
3) when wind < 1mph:
a) PFD shows 0mph and 0deg
d) MFD shows no wind arrow
4) slight performance increase by shortcutting when on the ground
=> PFD and MFD wind bug fixes

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DepArrPage.js
- improved formatting of DEP page
- dont navigate away from page on EXEC
=> Improve DEP Formatting

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
- fixes pagination / pageinfo
- go back to correct page after edit
- INSERT waypoints into flight plan
=> FPLN Improvements

build.ps1, src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4/Index.xml, src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4/Lighting.xml, src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4/Passenger.xml, src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4/Subtemplates/Passenger_Subtemplates.xml, src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/engines.cfg, src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/model/CJ4_Cockpit.xml, src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/sound/sound.xml, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/PFD/AirspeedIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DirectToPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PosInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC_Renderer.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html
Integrate changes from patch 1.9.3 for the cj4
=> CJ4 Integrate 1.9.3

.github/workflows/workingtitle-cj4-prerelease.yml, .github/workflows/workingtitle-cj4-release.yml, PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, docs/workingtitle-cj4/CHANGES.md, docs/workingtitle-cj4/Working Title CJ4 v0.2.0 Changes.md, workingtitle-project-cj4meta.xml
New one cause the other build was screwed by rebase ^^
=> Fix automatic building of package on Release

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DepArrPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.css
=> Cj4 Prerelease 0.3.1 bugfixes

src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js
the ones I overlooked while coding while tired last night.
=> extend track-up disable to remaining MFD waypoint info pages

src/workingtitle-vcockpits-instruments-navsystems-gx/README.md, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.css, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.html, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.js, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch_Buttons.css, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/MFD/mapConfig.json, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/PFD/mapConfig.json, src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
This starts fleshing out support for the G3X Touch system.
=> Add G3X Touch support

src/.eslintrc.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FuelMgmtPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PosInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC_Renderer.js
* show (DIR) when flight plan is direct to
* fix timers
*  fix timer on LEGS after input
*  Legs only show decimals < 100nm
=> CJ4: Legs fixes pre 0.4.0

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DepArrPage.js
Arrivals: Enable paging for transitions, e.g. EDDK: NVO transition is selectable now
Arrival/Approach Filter: trailing space in approach runway does not prevent match, e.g. EDDC
Minor improvements to arrivals and departure pages
=> CJ4: dep/arr page fixes

src/workingtitle-aircraft-tbm930/SimObjects/Airplanes/Asobo_TBM930/model/TBM930_interior.xml, src/workingtitle-base-aircraft-common/ModelBehaviorDefs/Asobo/GlassCockpit/AS3000.xml, src/workingtitle-base-aircraft-common/ModelBehaviorDefs/Asobo/GlassCockpit/AS580.xml, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/AS3000_Common.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/MFD/AS3000_MFD.css, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/MFD/AS3000_MFD.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.css, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/AS3000_TSC_Common.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Horizontal/AS3000_TSC_Horizontal.css, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Horizontal/AS3000_TSC_Horizontal.html, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/MapInstrument.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgLabeledRingElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgMap.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRangeCompassElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRangeRingElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRoadNetworkElement.js
Converted all the tabs in my source code to spaces.
=> converted all tabs to spaces

src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/AS3000_Common.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/MFD/AS3000_MFD.html, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.html, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Horizontal/AS3000_TSC_Horizontal.css, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Horizontal/AS3000_TSC_Horizontal.html, src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
... and to the PFD_Attitude in CommonPFD_MFD while we're at it.
=> add data storage backing to all G3000 TSC settings 

src/.eslintrc.json, src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/systems.cfg, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_ModSettingsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js
=> CJ4: Add Modsettings page, add dimmable passenger cabin lights

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_TakeoffRefPage.js
=> Simple PR to fix the REF pages black screen and provide additional input protection

.editorconfig
Makes merging/diffing a lot easier
=> trim_trailing_whitespace added to editor config

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DepArrPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js
=> Cj4: DepArr added vfr landing runways, departure transitions, arrival transitions, perf init updates

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js
Enables skipping approach fixes by dropping them onto magenta.
DEMO: https://streamable.com/83v3kn
=> CJ4: Skip approach fixes in legs

src/.eslintrc.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DirectToPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DsplMenuPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC.css
To indicate that a page is not implemented yet, I would like to add this style to it. 
I think it makes for a much better experience to know if a page actually does something.
Probably helps us too to figure out where to work on.
=> CJ4: Add a disabled style to INOP menu items

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_MsgPage.js
Small update while I study the project and see what I can work on
=> CJ4: Added message page and enabled MSG button function

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DsplMenuPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js
Disables RNG: ALT SEL, GNSS POS, ALTN PPLN on DSPL MENU
Disables FMS CTL, TEMP COMP in Index Page 2
=> CJ4: Disabled more non-functional menus

src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4/Control.xml, src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/model/CJ4_Cockpit.xml, src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/panel/panel.xml, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/MFD_WTMenu.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD_Checklist.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD_Storage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
- restructured Lower MFD menu
- improved usability of MFD checklist
- FMS text will now stay opened after opening MFD checklist or passenger briefing
- added functionality to CCP MEM buttons, allowing users to save states of the MFD and switch quickly between them
- Fixed broken fuel reading on SYSTEM OVERLAY menu
We need to padspace all the navbar values so that they don't jump around.
closes #246 
closes #249
=> CJ4: MFD Overhaul

src/.eslintrc.json, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/NDInfo.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
- added elapsed timer functionality to PFD
- restructured PFD menu
- Fix error when AOA was set to on/off and you couldn't open the PFD Menu anymore / closes #251
=> CJ4: PFD Improvements

docs/workingtitle-cj4/CHANGES.md, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js
=> ARR DATA page improvements

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD_Storage.js
Noticed while working on UI version of checklists 😋
=> CJ4: One typo in mfd checklists LOL :)

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js
Did some minor tweaks. It seems to work better now.
https://streamable.com/mmjwz9
Please test test test
=> CJ4: Fix direct to approach fixes

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FplnRecallPage.js
=> CJ4: Fix skipping departure in simbrief

README.md, docs/workingtitle-g3000/CHANGES.md, docs/workingtitle-g3000/README.md, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.js, src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgFuelRingElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgNearestAirportElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgNearestIntersectionElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgObstacleElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRangeCompassElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRangeRingElement.js
Hotfix release.
- resolves #311 
- resolves #313
- fixes issue with INT waypoint and airport symbols with G1000
- performance optimizations for range ring/compass and fuel ring
=> Release/g3000 v0.2.1

.github/workflows/workingtitle-cj4-prerelease.yml, .github/workflows/workingtitle-cj4-release.yml, PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, README.md, docs/workingtitle-cj4/CHANGES.md, docs/workingtitle-cj4/Working Title CJ4 v0.5.0 Changes.md, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js
=> CJ4: 0.5.1 Prerelease

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
Fix Elevator Trim Indicators so they move the right direction along with a change to CJ4_SHARED.js
=> Update CJ4_MFD.js Fix Elevator Trim Indicators

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
Fix Elevator Trim Indicators so they move the right direction along with a change to CJ4_MFD.JS
=> Update CJ4_Shared.js Fix Elevator Trim Indicators

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js
Now you should not be able to CLR approach fixes or insert something into their position.
closes #342
=> CJ4: Block mods on approach fixes

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_TakeoffRefPage.js
-Removed incorrect error message for no departure runway loaded
-Added QNH that automatically gets pulled from the PFD baro setting (currently not able to set it yourself.  No point?)
-With no runway or OAT entered, the TOFL, runway length, and vspeeds will be blank.
-When a runway is loaded, the runway length will be shown.
-Added input checks for OAT (-54 to +54) and 0 can now be entered without error.
-Calm winds can now be entered by leaving the wind fields blank without getting an error.
Closes #334
=> CJ4: Takeoff Ref Input Checks

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/NDInfo.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
=> CJ4: Added Bearing Pointers

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
=> CJ4:  Fix ISA temp calculation on MFD

src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/MFD/mapConfig.json, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/InnerMapConfig/mapConfig.json, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgAltitudeInterceptElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgFuelRingElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgLabeledRingElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgMapElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRangeCompassElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgRangeRingElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgTrackVectorElement.js
Updated range ring, range compass, track vector, fuel ring, and altitude intercept arc to import settings from mapConfig.json. Settings not explicity set in mapConfig will revert to default values defined in the code.
=> mapConfig support for new map overlays

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
This changes the hydraulic pressure values so that it is tied to N2 and scales properly so full (and normal) system pressure of 3000psi is reach by 20% N2.
=> CJ4: MFD Corrected Hydraulic Values

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js
Add Transponder STBY/ALT to TUN Page 1 and set transponder mode to STBY in CJ4_FMC constructor
@dga711 please confirm I did it correctly as the TUN page is new format.
=> CJ4: Add Transponder STBY/ALT Functionality

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AltimeterIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html
=> CJ4: Overhaul of altimeter styles 

docs/workingtitle-cj4/CHANGES.md, docs/workingtitle-cj4/Working Title CJ4 v0.5.1 Changes.md, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AirspeedIndicator.js, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/FlightPlanManager.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
=> CJ4: 0.6.0 prerelease

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
* Setting Origin clears the whole flight plan
* Setting Destination should clear all procedures
* Show "NOT ON GROUND" when setting origin while airborne
=> CJ4: Some FPLN improvements

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD_Storage.js
This PR will store and load MFD Presets from datastorage.
=> CJ4: Persistent stored MFD MEM function

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/NDCompass.js
I've added the basic SVGs for the upgraded course needles.
Work still left to be done:
1) Add logic for the TO/FROM arrow to flip according to passing station logic
2) Make it so the courseTO arrow is not filled in
3) Add the courseFROM arrow.
4) Add this style of needle to show up when in FMS nav and point to desired course with track deviation CDI.
=> CJ4: Added Course Needles for VOR

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_ModSettingsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
=> CJ4: Persistent cabinlights setting

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FuelMgmtPage.js
Solution by @Wombii (need to credit in changelog)
Closes #256
=> CJ4: Fix refresh of FuelMgmt

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
=> FPLN: Dont clear temporary flight plan on error

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_SelectWptPage.js
only shows duplicates (exact ident matches)
sorts by distance
reformat display to be more reflective of reality
closes #428
=> CJ4: Waypoint Select Page Improvements

src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/systems.cfg, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_ModSettingsPage.js
CJ4: GPU Switch in Mod Settings + added to systems.cfg
=> CJ4: GPU Switch in Mod Settings + added to systems.cfg

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
=> CJ4: Cabinlights now tied to battery on/off

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PosInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC_Renderer.js
**updated** (see conversation below) 
~~[example of the problem](https://streamable.com/u0pn96), at least I think it's a problem :)))~~
~~Tested on several pages, didn't see any adverse behaviour, but you use this function in many places, so idk.~~
=> CJ4: Revamped (a little) error messages in the FMC

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC_Renderer.js
=> CJ4: Oops, forgot to remove console.logs

src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/MFD/AS3000_MFD.js, src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.js, src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/MapInstrument.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgFlightPlanElement.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgMapConfig.js
Updates g3000 files, MapInstrument-related files, and CommonPFD_MFD.js for compatibility with 1.10.7.0.
=> G3000/MapInstrument patch 1.10.7.0 compatibility fixes

src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.css, src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js, src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/PFD/AS1000_PFD.js, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.css, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Utils/XMLLogic.js
=> 1.10 update backports

PackageDefinitions/workingtitle-g1000-metapackage.xml, docs/workingtitle-g1000/CHANGES.md, docs/workingtitle-g1000/README.md, src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.css, src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js, src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/PFD/AS1000_PFD.js, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.css, src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Utils/XMLLogic.js
=> doc updates for g1000 0.3.2

README.md, docs/workingtitle-g3000/CHANGES.md, docs/workingtitle-g3000/README.md
=> updated g3000 docs for v0.2.2

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_SelectWptPage.js
Fixes issue with next and prev page failing on the waypoint select page.
closes #442
=> CJ4: Fixes WaypointSelectPage not showing Next Page

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_SelectWptPage.js
Shifted R and L button press code to match new format
=> CJ4: Enhancement - Waypoint Select Page Improvements

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
=> Fixed issue where bearing pointers appear on PLAN view

PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DsplMenuPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/mapConfig.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/mapConfig.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgAltitudeInterceptElement.js, workingtitle-project-cj4.xml
Thanks to @cywang90 
**Before Merge**
> whenever you guys release/merge the svgaltitudeinterceptelement changes into main let the rest of us know because we will have to update the garmin stuff
=> CJ4: Alt Banana

src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgMap.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgTextManager.js, src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/Svg/SvgWaypointElement.js
- fixed labels for flight plan waypoints sometimes disappearing
- fixed labels not showing when preventLabelOverlap = false is set in mapconfig.json
- fixed city labels appearing in the weather radar screens
=> NavMap: waypoint label fixes

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_SelectWptPage.js
=> CJ4: Ignore undefined waypoints in SelectWPT logic

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/mapConfig.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/mapConfig.json
active leg magenta, non active white, labels all white
=> CJ4: 0.7.1 bug fix: active leg magenta, non active white, labels all white

PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, PackageDefinitions/workingtitle-aircraft-cj4.xml, docs/workingtitle-cj4/CHANGES.md, docs/workingtitle-cj4/README.md, docs/workingtitle-cj4/Working Title CJ4 v0.7.0 Changes.md, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DsplMenuPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FuelMgmtPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/mapConfig.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/mapConfig.json, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
**TODO:**
**Bugs:**
**Features:**
=> CJ4: 0.7.1 Pre-Release

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_ModSettingsPage.js
=> CJ4: Fix game FPLN sync option

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/wtsdk/src/flightplanning/FlightPlanManager.ts
=> CJ4: Fix ARR DATA errors

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/BaseNDCompass.js
Using our custom LVar now to see if HDG mode is actually active
=> CJ4: Fix HDG select line always showing when in LNAV too

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
fix mach value in FMA to 2 significant digits
=> CJ4: fix mach value in FMA to 2 significant digits

PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, workingtitle-project-cj4.xml
=> CJ4: Remove vcockpits-instruments package from cj4 builds

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/SAI/CJ4_SAI.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/SAI/CJ4_SAI.html, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/SAI/CJ4_SAI.js
This brings in the SAI Altimeter Setting rounding error fix from Hosky's QoL branch.
=> CJ4: Bring in SAI to fix altimeter setting rounding error

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
Fixes the Origin/Dest click logic as follows:
1) Clicking the LSK with nothing in the scratchpad and a fix in the Origin/Dest will put it into the scratchpad
2) Click the LSK with nothing in the scratchpad and nothing in Origin/Dest will do nothing.
=> Route page fix

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC.css, src/wtsdk/src/flightplanning/FlightPlanAsoboSync.ts
Fixes a problem in game fp import when the departure contained VECT-like legs
=> CJ4: Fix problem in game fp import

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
=> CJ4: FPLN fix update problems on modification

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseLnav.js, src/wtsdk/src/flightplanning/ManagedFlightPlan.ts
Fixed negative values in base lnav and in the FPM.
=> Cj4: Fix LNAV negative values

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FplnRecallPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_VNavSetupPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/CJ4NavModeSelector.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseLnav.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseVnav.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_VnavAutopilot.js, src/wtsdk/src/flightplanning/FlightPlanManager.ts, src/wtsdk/src/flightplanning/ManagedFlightPlan.ts, src/wtsdk/src/flightplanning/WaypointBuilder.ts
=> CJ4: GP Calc & LEGS Page Enhancements

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js
=> CJ4: Fix LEGS blackout when flight plan is empty

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AttitudeIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
Adds cross pointer flight director, toggle-able through the PFD menu.
Things to do:
=> Cj4 cross pointers fd

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/ILSIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseLnav.js
=> CJ4: Refactor PFD ILS/LDEV/VDEV

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/NDCompass.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/WTLibs/MapInstrument.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/WTLibs/Svg/SvgWaypointElement.js, src/wtsdk/src/flightplanning/FlightPlanManager.ts
=> CJ4: Fix bugs on PFD/MFD map

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/WTLibs/Svg/SvgFlightPlanElement.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/WTLibs/Svg/SvgWaypointElement.js
=> CJ4: Holds Bugfixes

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/HoldsDirector.js
When the hold course is not true, then correct for the magnetic variation at the initial hold fix.
We could calculate magnetic variation at each fix, but it is unlikely that the variation will be extreme between hold fixes.
Images showing the 114M/R published hold at SEETS on the JFUND2 arrival into KBOS properly aligned with the arrival.
=> Correct hold fix calculation for magnetic variation

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FuelMgmtPage.js
=> Fix fuel timing calculation and display

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/NDInfo.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js
Addresses #687 and #796.
Also adds support for fractional ADF frequencies.
=> Fixed issue where DME only stations would not show on either the main or the brg ptr data blocks.

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js
=> Fix perf init crz alt input

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/ILSIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
=> CJ4: Ghost LOC/GS on PFD

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.css, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html
Normal AP mods will work as expected without, but strikethrough needs js integration, @mattnischan has been informed.
=> CJ4/Simplified FMA strikethrough

src/workingtitle-aircraft-cj4/ModelBehaviorDefs/Asobo_CJ4/WT_Autopilot.xml, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AltimeterIndicator.js
Baro Preset function ready for testing and merge.
=> Cj4 baro preset

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js
-Minor cosmetic changes to match real aircraft
-Modified PAGE 2/2 to remove ADF 1 and ADF 2 to match real unit and prevent user confusion
-Added ATC CONTROL page
-Added Dispatch page when avionics switch set to DISPATCH mode. - WIP
-Added code for ATC CONTROL and DISPATCH mode - needs review.
=> CJ4-tunepg-updates

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
Further enhancement of terrain colors.
- adds curve points above and below aircraft based on aircraft AGL altitude.
- I hate aspen
=> CJ4-Terrain-REDUX

PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, PackageDefinitions/workingtitle-aircraft-cj4.xml, README.md, docs/workingtitle-cj4/CHANGES.md, docs/workingtitle-cj4/Working Title CJ4 v0.12.0 Changes.md, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DsplMenuPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/CJ4NavModeSelector.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/LNavDirector.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_VnavAutopilot.js, src/wtsdk/src/flightplanning/FlightPlanManager.ts, src/wtsdk/src/flightplanning/LegsProcedure.ts, src/wtsdk/src/flightplanning/ManagedFlightPlan.ts, src/wtsdk/src/utils/SimVarCache.ts
=> CJ4 v0.12.1 Prerelease

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/VerticalSpeedIndicator.js
=> Improved V-Speed band

PackageDefinitions/workingtitle-g1000-metapackage.xml, docs/workingtitle-g1000/CHANGES.md, src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/Templates/XMLEngineDisplay/XMLEngineDisplay.js
[x] Fixed issue with inop MFD range knob
=> G1000 0.4.1 Prerelease

src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AirspeedIndicator.js, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AltimeterIndicator.js, src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AttitudeIndicator.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.css
Converted text strokes to text shadows, for Mach indicator, Altimeter Setting, VNAV Constraint, and RA.
As Implemented:
Reference:
=> CJ4 PFD: Converted text strokes to text shadows.

README.md
=> Update Readme (latest G3000 link)

src/wtsdk/src/flightplanning/FlightPlanManager.ts
=> Fixed issue where nav-to-nav could not validate correct freq was tuned due to float precision

PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, PackageDefinitions/workingtitle-aircraft-cj4.xml, docs/workingtitle-cj4/Working Title CJ4 v0.12.9 Changes.md, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/LNavDirector.js, src/wtsdk/src/flightplanning/FlightPlanManager.ts
=> CJ4 Prerelease 0.12.10

PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml, PackageDefinitions/workingtitle-aircraft-cj4.xml, README.md, docs/workingtitle-cj4/README.md, docs/workingtitle-cj4/Working Title CJ4 v0.12.11 Changes.md, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
=> Cj4 prerelease 0.12.12

src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/sound/sound.xml, src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
Fixes the warning/caution tones. 
Had to pull in some of the stock logic since the actual playSound IDs were hardcoded
Will replace 12.12 tag and release after merge for the "hotfix"
=> CJ4: Fix warning/caution tones

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_NavRadioPage.js
Implemented IDENT functionality in the Nav Radio.
Button is initially white until pressed then turns blue for 10 seconds.
This timing is for vPilot.
=> CJ4: Implemented IDENT button in NavRadio

src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/LNavDirector.js
add AutopilotMath.normalizeHeading to targetHeading in setCourse method
=> add AutopilotMath.normalizeHeading to targetHeading in setCourse method
