Working-Title-MSFS-Mods/fspackages

- .github/workflows/workingtitle-g1000-build.yml
- .github/workflows/workingtitle-g1000-prerelease.yml
- .github/workflows/workingtitle-g1000-release.yml
- docs/workingtitle-g1000/CHANGES.md
- docs/workingtitle-g1000/README.md
This modifies the workflow for the G1000 to cuz a release when a tag with a g1000-v* prefix is pushed to the repo.  There are two different versions, one for pre-releases and one for full releases.  Currently I have the releases being set as drafts to we can review them until there's confidence in the automation.
This does not yet have anything for creating a text description on releases, I'm thinking about the best way to handle that.
I'm creating this as a WIP PR to get comment on what I've done, and also see if you want me to include similar steps for the CJ4.
You can see the outputs of this process here:   https://github.com/Working-Title-MSFS-Mods/fspackages/releases
> WIP: tag-based release automation

- .gitignore
- jsconfig.json
Addresses #8.
This allows a developer to add stock files to folders in /ref (now added to .gitignore) to have VS Code understand the relationship between the JS files. This also will link between existing modified files by default.
> VS Code JS global imports support

- build.ps1
The filter for directories only in the file copy here made it skip any files in the top level of the package directory.  This will avoid that.
> removed directory filter from copies in build script

- README.md
- docs/workingtitle-g1000/README.md
The top of the repo looked so bare.  Especially since I'm going to share the new G1000 version soon I wanted to put _something_ there.   I welcome all comments on this. :)
> improve main repo readme, put version number into G1000 readme

- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/Shared/Utils/XMLLogic.js
The MaxSinceStart XML element is used to compute the "Altitude Loss After Takeoff" by subtracting the current altitue from the maximum altitude since start. This approach triggers a false TERRAIN / DON'T SINK alert when flying circuits / patterns or when performing touch and go landings.
To fix this issue reset the maximum value of the MaxSinceStart XML element when we are on ground.
> Fix false positive "DON'T SINK" alerts

- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
Fixes #21 
Before this patch:
```
fastToFixed(12.345, 4) -> "12.345"
fastToFixed(12, 1) -> "12"
```
After this patch:
```
fastToFixed(12.345, 4) -> "12.3450"
fastToFixed(12, 1) -> "12.0"
```
I also tested the performance impact of the new implementation and it is
about twice slower than the original one, however it is now correct and
much better then toFixed() which is about 20 times slower.
The tests were performed with the following script in Chrome
(JavaScript	V8 8.5.210.20):
```
a=performance.now();
for(let i=1; i<10000000; i++) {
fastToFixed(12.345, 1);
}
b=performance.now();
b-a
```
Before patch: 132.78999998874497
After patch: 230.62000000476837
toFixed: 1958.7400000020862
> Reimplement fastToFixed function to include trailing zeros.

- build.ps1
When the build.ps1 is now run with the argument `-WatchFiles $true` it will watch for file changes in the `src` folder.
On a file change, it will automatically run the build routine.
+ Use robocopy to only copy modified files to build output
+ New parameter `$CleanBuild` to clean the output path before build
> Build.ps1: Implement Filewatcher for automatic builds

- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/Templates/Altimeter/Altimeter.js
When switching the barometric pressure unit (from inches to HPA and
viceversa) the shown barometric pressure value is reset to 29.92IN
(or HPA equivalent).
Save the barometric pressure updates in the local thisPressure field
and use it to update the HTML text either when the pressure changes or
when the unit changes.
> Altimeter: show correct barometric pressure when switching unit

- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/AS1000/PFD/AS1000_PFD.html
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/AS1000/Shared/BaseAS1000.js
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/Templates/Altimeter/Altimeter.js
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/Templates/HSIndicator/HSIndicator.js
This adds support for persistent (per plane) PFD settings using the existing dataStorage APIs.
The following settings are currently implemented: wind data mode, reference speeds values and enable/disable state, bearing source and DME visible / not visible, barometric pressure unit.
> Persistent PFD settings

- src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/engines.cfg
Without this, keyboard/gamepad users are still able to reverse throttle using the "decrease throttle" game mapping (defaults: "B" for Xbox controller and F2 for keyboard) if they push the button so throttle decreases past zero, so to speak. Even though the plane moves slightly forward. Go figure ¯\\_(ツ)_/¯
Pretty sure it doesn't affect engine performance. At least numbers are the same.
> [CJ4]: Remove reverse throttle for keyboard and gamepad users

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
This PR adds the AoA On/Off/Auto setting to the PFD by creating a new LVAR for AoA .
The pop up menu on the PFD was modified to reorder the CONFIG settings, remove the 'UNITS' submenu as that's not true to the real aircraft and added the AoA setting line.
The AoA itself is now hidden whenever AoA is set to OFF, or when flaps are not at 35 and AoA is set to AUTO. When AoA is set to ON it appears always.
```
L:WT_CJ4_PFD1_AOA
0 = Auto
1 = On
2 = Off
```
> AoA On Off Auto Setting

- docs/workingtitle-g1000/CHANGES.md
- src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js
- src/workingtitle-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/WorkingTitle/MapInstrument.js
this allows the temporary disabling of drawing things track-up so that we can present WPT info without rotating the map.  This also avoids major CSS layer ugliness that we'd have to resolve.
> fix map being drawn track up and ugly in WPT

- build.ps1
Earlier I added the PURGE argument to robocopy to remove files in the output that are not in source anymore.
But it turned out to work badly on packages with multiple assetgroups, as the former would always get deleted. So I removed it for now.
> buildps1: remove purge argument

- README.md
adding some badges to the readme
* discord
* github download count
* contributor count
would love to add a badge for latest version. but i can't make it so it can distinguish between cj4 and gx mods
> Readme: Added badges

- PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml
- PackageDefinitions/workingtitle-core-library.xml
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.html
- workingtitle-project-cj4.xml
This includes the core library into both of the cj4 project files and imports it into the CJ4 FMC so it can be used without needing to be pulled into every script.
> add core library to cj4 and cj4meta projects

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
ETE and Landing time would continually update and never stop.
> CJ4: Fix calculation bugs in the FMS Flight Log Page

- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/AS3000_Common.js
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/MapElement.js
Renamed WTMapSymbolRangeSetting to WT_MapSymbolRangeSetting to be underscore style-compliant.
> fixed missing underscore in WTMapSymbolRangeSetting

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
Pulling wrong VAR was the cause and now works and display's correct value. Should fix issue #250
> CJ4: Fixes FLC Mach Climb display on AP Tape

- .gitignore
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
From what I can tell seems battery load is actually tracked in WATTs (comments in Systems,cfg under item power from OSBO) not amps, Appling the Watts to Amps conversion formula seems to display correct values.
> CJ4: Fixes Battery Amps Display in ECIS and SYS pages. 

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FplnRecallPage.js
Shows an error when import is cancelled because of an invalid airway or waypoint
> SimBrief: Show error when wpt or airway invalid

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_TakeoffRefPage.js
No matter what you punch in, QNH was always shown/set according to "KOHLSMAN SETTING HG" value.
> CJ4: Show/use punched in qnh on takeoff perf page

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DepArrPage.js
The idea of this PR: When pressing DEPARR, go directly to the depature or the arrival page, depending on the current situation.
The logic is as follows:
- Origin set and airplane on the ground -> Departure page
- Origin set and airborne and no destination set and less than 50nm away from origin -> Departure page
- Origin set and airborne and destination set and (less than 50nm away from origin AND not halfway through to destination) -> Departure page
- Origin set and airborne and destination set and (more than 50nm away from origin OR halfway through to destination) -> Arrival page
Index page in all other situations, these are:
- No origin (don't care about destination) -> Index page
- Origin set and airborne and no destination and more than 50nm away from origin -> Index page
Press …
> CJ4 deparr direct entry

- src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/model/CJ4_Cockpit.xml
Doesn't do anything on it's own, but when I finish #122 (hopefully with the help from @dga711) this will be needed for highlighting some of the knobs and buttons.
Also, does anyone know how to change default position of knobs? Specifically "pressure source selector" should be on "norm" all the time. I assume @J-Hoskin knows this stuff :)
> CJ4: Add highlighting for some of the knobs (for ui checklist stuff)

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_ApproachRefPage.js
@cwburnett @dga711 getApproachRunway() == undefined if user did not select an approach. You guard against this in other places, but not here. And they ask me why I hate javascript 😋
> CJ4: Hotfix arrival speeds calculation

- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/AS3000_TSC_Common.js
- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Horizontal/AS3000_TSC_Horizontal.html
- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Vertical/AS3000_TSC_Vertical.html
Change the window title of the map sync settings from "Map Orientation" to "Map Sync Settings" as specified in https://static.garmin.com/pumac/190-02046-02_a.pdf on page 202.
I also removed some seemingly duplicate code.
> G3000: Change window title of the map sync settings

- .gitignore
- src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.html
- src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/MFD/AS1000_MFD.js
- src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/PFD/AS1000_PFD.html
- src/workingtitle-vcockpits-instruments-navsystems-g1000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS1000/Shared/BaseAS1000.js
- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/PFD/AS3000_PFD.html
- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/AS3000_TSC_Common.js
- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Horizontal/AS3000_TSC_Horizontal.html
- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3000/TSC/Vertical/AS3000_TSC_Vertical.html
- src/workingtitle-vcockpits-instruments-navsystems-gx/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/AS3X_Touch/AS3X_Touch.html
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/CommonPFD_MFD.js
On some screens the conversion of the runway length and width from meters to feet was omitted but the unit "FT" was still displayed. Note that the different runway lengths are simply because this airport has two different runways and on some pictures the longest one is shown and on other screens you can select one.
* MFD Nearest Airports BEFORE
* MFD Nearest Airports AFTER
* PFD Airport Information BEFORE
* PFD Airport Information AFTER
I also changed the code for some other locations that use the runway dimensions but these already worked before:
* MFD Airport Information
* PFD Nearest Airports
* TSC Airport Information
> Various Garmins: Add missing conversions of the runway length/width from meters to feet

- src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/model/CJ4_Cockpit.xml
- src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/panel/panel.xml
- src/workingtitle-base-aircraft-common/ModelBehaviorDefs/Asobo/GlassCockpit/AS3000.xml
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.css
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.html
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.html
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
- src/workingtitle-vcockpits-instruments-navsystems/html_ui/WorkingTitle/Pages/VCockpit/Instruments/NavSystems/Shared/WT_SystemAnnunciations.js
- workingtitle-project-cj4.xml
- Changes styling of CAS messages to fit more closely with the real aircraft
- Removes warning and caution tones that play when a CAS message is displayed
- Redid almost all CAS messages to reflect real aircraft conditions, leaving out failure related messages and those relying on systems not yet modelled (pressurisation)
- Added functionality to the CAS Message CCP button to open and close CAS messages menu when non-caution and non-warning messages are shown. Not 100% real behaviour of real aircraft, but until split MFD, it gets around advisory messages always showing.
- Fixes #393
**Requires #480**
> CAS Overhaul

- src/sound/Actor-Mixer Hierarchy/AIRCRAFTS/AIRCRAFT_WWISEDATA/AIRCRAFT_PLAYER/Wind.wwu
Puts wind back on the winds_generic_inside bus so it won't continue playing at game pause.
closes #620
> Change wind to correct bus

- src/sound/Actor-Mixer Hierarchy/AIRCRAFTS/AIRCRAFT_WWISEDATA/AIRCRAFT_PLAYER/Engines.wwu
Removes the reverb effect from the exterior engine start so it blends easier with the idle loop so you don't go from the wide stereo field to almost mono.
> Change engine start to remove reverb

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/WT_FMC_Renderer.js
Fixing a problem in the renderer the FMS now comes back on when you press a button for other pages.
> CJ4: Fix fatal FMS black out

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FplnRecallPage.js
SimBrief sends for ex. 3U2 as K3U2 and the sim doesnt like it.
If there is a number after K, it will strip the K and add a space at the end so the sim takes it.
> CJ4: Fix SimBrief handling of three letter airports

- src/wtsdk/src/flightplanning/FlightPlanAsoboSync.ts
- src/wtsdk/src/flightplanning/FlightPlanManager.ts
It is able to CTD the game. So get rid of it.
> CJ4: Remove active_waypoint_index coherent calls

- src/wtsdk/src/flightplanning/FlightPlanManager.ts
It calls set active wpt and recompute wpt on every flight start.
Just some magic sauce in the hopes that non synced flight plans created in world map could like it better. Then. Shouldn't hurt.
> CJ4: FPLN CTD magic sauce

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/PFD/CJ4_PFD.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/CJ4NavModeSelector.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseLnav.js
> CJ4: 0.8.5 pre pre bugfixes

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DepArrPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DirectToPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_HoldsPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_LegsPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_SelectWptPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/HoldsDirector.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseLnav.js
- src/wtsdk/src/flightplanning/FlightPlanManager.ts
- src/wtsdk/src/flightplanning/WaypointBuilder.ts
> CJ4: Various legs, hold, dep/arr fixes

- PackageDefinitions/workingtitle-aircraft-cj4-metapackage.xml
- PackageDefinitions/workingtitle-aircraft-cj4.xml
- README.md
- docs/workingtitle-cj4/CHANGES.md
- docs/workingtitle-cj4/Working Title CJ4 v0.9.0 Changes.md
- src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/AirspeedIndicator.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_DirectToPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_InitRefIndexPage.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/HoldsDirector.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/Autopilot/WT_BaseLnav.js
- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/WTLibs/Svg/SvgFlightPlanElement.js
> CJ4: 0.9.1 Prerelease

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js
This should make it so you can insert airways in between legs on the flightplan even when procedures are set. Not only at the end.
> CJ4: Fix airway entry in between flight plan

- src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/BaseNDCompass.js
- src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/NDInfo.js
-Allows the option to change the course of VOR1 and VOR2 with the CRS1 knob without having any VOR tuned in and within range.
-Shows the needle course on the navaid datablock
-Also allows changing of the localizer course but only when the aircraft isn't in ARMED mode for NAV-to-NAV transfer.
> Cj4 change vor course

- src/workingtitle-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/WT/BaseNDCompass.js
Adjustments:
Will now autotune while in either FMS or LOC/VOR needles and while in NavToNavState 3 (armed).  The needle will not be able to be moved with the CRS knob during that NavToNav state but there's no reason to.
> Cj4 fix course change again

- src/workingtitle-vcockpits-instruments-navsystems-g3000/html_ui/WTg3000/SDK/Airplane/PlayerAirplane.js
The mod changes ATC MODEL to "TT:ATCCOM.AC_MODEL_LONGITUDE.0.text"
> Fix G3000 with Longitude Flight Dynamics mod

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js
paxWeight was used both for calculating the zero fuel weight, but also for displaying the weight per passenger.
While the weight per passenger would display correctly, it would be calculated incorrectly with a lower weight due to all calculations being done in lbs.
This commit postpones conversion of paxWeight until displaying the value, which seems to be the norm.
Fixes #1102. Hopefully.
> fix(cj4): only use lbs paxWeight for zero fuel weight

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_FplnRecallPage.js
Skip unrecognized waypoints and continue when importing Flightplan from SimBrief
> Skip unrecognized waypoints when importing Flightplan from SimBrief

- src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC.js
Increased the maximum display brightness. Displays are now legible even in the brightest, most glary conditions. Users are still able to reduce brightness with the brightness control.
> CJ4 - Display brightness turned up to eleven
